name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version or commit hash
      placeholder: Output of git rev-parse HEAD, release version, or repos file
      value: rolling
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Steps to reproduce issue and expected behavior
      placeholder: Detailed instructions on what the issue is and how to reliably reproduce this issue http://sscce.org/. Code that can be copy-pasted is preferred.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Tell us what happens instead
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Backtrace or Console output
      placeholder: Use a GitHub Gist to copy-paste the console output or segfault backtrace using gdb.
    validations:
      required: false
