name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version or commit hash
      placeholder: Output of git rev-parse HEAD, release version, or repos file
    validations:
      required: true

  - type: dropdown
    id: rmw_implementation
    attributes:
      label: RMW Implementation
      options:
        - FastRTPS
        - CycloneDDS
        - RTIConnextDDS
        - Other
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce issue
      placeholder: Detailed instructions on how to reliably reproduce this issue http://sscce.org/. Code that can be copy-pasted is preferred.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Tell us what happens instead
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Backtrace or Console output
      placeholder: Use a GitHub Gist to copy-paste the console output or segfault backtrace using gdb.
    validations:
      required: false
