name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      placeholder: Description in a few sentences what the feature consists of and what problem it will solve
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation considerations
      placeholder: Relevant information on how the feature could be implemented and pros and cons of the different solutions
    validations:
      required: true
